<<HOL message: Created theory "m0Types">>
Saved theorem _____ "num2privcmd_privcmd2num"
Saved theorem _____ "privcmd2num_num2privcmd"
Saved theorem _____ "num2privcmd_11"
Saved theorem _____ "privcmd2num_11"
Saved theorem _____ "num2privcmd_ONTO"
Saved theorem _____ "privcmd2num_ONTO"
Saved theorem _____ "num2privcmd_thm"
Saved theorem _____ "privcmd2num_thm"
Saved theorem _____ "privcmd_EQ_privcmd"
Saved theorem _____ "privcmd_case_def"
Saved theorem _____ "datatype_privcmd"
Saved theorem _____ "privcmd_distinct"
Saved theorem _____ "privcmd_case_cong"
Saved theorem _____ "privcmd_nchotomy"
Saved theorem _____ "privcmd_Axiom"
Saved theorem _____ "privcmd_induction"
<<HOL message: Defined type: "privcmd">>
Saved theorem _____ "privcmd_distinct_clauses"
Saved theorem _____ "num2npriv_npriv2num"
Saved theorem _____ "npriv2num_num2npriv"
Saved theorem _____ "num2npriv_11"
Saved theorem _____ "npriv2num_11"
Saved theorem _____ "num2npriv_ONTO"
Saved theorem _____ "npriv2num_ONTO"
Saved theorem _____ "num2npriv_thm"
Saved theorem _____ "npriv2num_thm"
Saved theorem _____ "npriv_EQ_npriv"
Saved theorem _____ "npriv_case_def"
Saved theorem _____ "datatype_npriv"
Saved theorem _____ "npriv_case_cong"
Saved theorem _____ "npriv_nchotomy"
Saved theorem _____ "npriv_Axiom"
Saved theorem _____ "npriv_induction"
<<HOL message: Defined type: "npriv">>
Saved theorem _____ "datatype_command"
Saved theorem _____ "command_11"
Saved theorem _____ "command_distinct"
Saved theorem _____ "command_case_cong"
Saved theorem _____ "command_nchotomy"
Saved theorem _____ "command_Axiom"
Saved theorem _____ "command_induction"
<<HOL message: Defined type: "command">>
Saved theorem _____ "command_distinct_clauses"
Saved theorem _____ "command_one_one"
Saved theorem _____ "num2state_state2num"
Saved theorem _____ "state2num_num2state"
Saved theorem _____ "num2state_11"
Saved theorem _____ "state2num_11"
Saved theorem _____ "num2state_ONTO"
Saved theorem _____ "state2num_ONTO"
Saved theorem _____ "num2state_thm"
Saved theorem _____ "state2num_thm"
Saved theorem _____ "state_EQ_state"
Saved theorem _____ "state_case_def"
Saved theorem _____ "datatype_state"
Saved theorem _____ "state_distinct"
Saved theorem _____ "state_case_cong"
Saved theorem _____ "state_nchotomy"
Saved theorem _____ "state_Axiom"
Saved theorem _____ "state_induction"
<<HOL message: Defined type: "state">>
Saved theorem _____ "state_distinct_clauses"
Saved theorem _____ "num2output_output2num"
Saved theorem _____ "output2num_num2output"
Saved theorem _____ "num2output_11"
Saved theorem _____ "output2num_11"
Saved theorem _____ "num2output_ONTO"
Saved theorem _____ "output2num_ONTO"
Saved theorem _____ "num2output_thm"
Saved theorem _____ "output2num_thm"
Saved theorem _____ "output_EQ_output"
Saved theorem _____ "output_case_def"
Saved theorem _____ "datatype_output"
Saved theorem _____ "output_distinct"
Saved theorem _____ "output_case_cong"
Saved theorem _____ "output_nchotomy"
Saved theorem _____ "output_Axiom"
Saved theorem _____ "output_induction"
<<HOL message: Defined type: "output">>
Saved theorem _____ "output_distinct_clauses"
Exporting theory "m0Types" ... done.
Theory "m0Types" took 0.01821s to build
Completed load of m0TypesScript
