<<HOL message: Created theory "principal">>
Saved theorem _____ "datatype_authority"
Saved theorem _____ "authority_11"
Saved theorem _____ "authority_case_cong"
Saved theorem _____ "authority_nchotomy"
Saved theorem _____ "authority_Axiom"
Saved theorem _____ "authority_induction"
<<HOL message: Defined type: "authority">>
Saved theorem _____ "authority_one_one"
Saved theorem _____ "num2role_role2num"
Saved theorem _____ "role2num_num2role"
Saved theorem _____ "num2role_11"
Saved theorem _____ "role2num_11"
Saved theorem _____ "num2role_ONTO"
Saved theorem _____ "role2num_ONTO"
Saved theorem _____ "num2role_thm"
Saved theorem _____ "role2num_thm"
Saved theorem _____ "role_EQ_role"
Saved theorem _____ "role_case_def"
Saved theorem _____ "datatype_role"
Saved theorem _____ "role_distinct"
Saved theorem _____ "role_case_cong"
Saved theorem _____ "role_nchotomy"
Saved theorem _____ "role_Axiom"
Saved theorem _____ "role_induction"
<<HOL message: Defined type: "role">>
Saved theorem _____ "role_distinct_clauses"
Saved theorem _____ "num2staff_staff2num"
Saved theorem _____ "staff2num_num2staff"
Saved theorem _____ "num2staff_11"
Saved theorem _____ "staff2num_11"
Saved theorem _____ "num2staff_ONTO"
Saved theorem _____ "staff2num_ONTO"
Saved theorem _____ "num2staff_thm"
Saved theorem _____ "staff2num_thm"
Saved theorem _____ "staff_EQ_staff"
Saved theorem _____ "staff_case_def"
Saved theorem _____ "datatype_staff"
Saved theorem _____ "staff_distinct"
Saved theorem _____ "staff_case_cong"
Saved theorem _____ "staff_nchotomy"
Saved theorem _____ "staff_Axiom"
Saved theorem _____ "staff_induction"
<<HOL message: Defined type: "staff">>
Saved theorem _____ "staff_distinct_clauses"
Saved theorem _____ "datatype_principal"
Saved theorem _____ "principal_11"
Saved theorem _____ "principal_distinct"
Saved theorem _____ "principal_case_cong"
Saved theorem _____ "principal_nchotomy"
Saved theorem _____ "principal_Axiom"
Saved theorem _____ "principal_induction"
<<HOL message: Defined type: "principal">>
Saved theorem _____ "principal_distinct_clauses"
Saved theorem _____ "principal_one_one"
Exporting theory "principal" ... done.
Theory "principal" took 0.03767s to build
Completed load of principalScript
