# ===================================================
# Makefile for example1 Theory 
# ===================================================

PDFLATEX=pdflatex
DVILATEX=latex
MAKEINDEX=makeindex
BIBTEX=bibtex

default: report

clean:
	(rm -f *Report.* HOL*.*)

report:
	hol<documentation.sml
	${PDFLATEX} SM0r3SolutionsReport
	${MAKEINDEX} SM0r3SolutionsReport
	${PDFLATEX} SM0r3SolutionsReport

