# ===================================================
# Makefile for HW 
# ===================================================

default: theory

clean:
	cd HOL;make clean;
	cd Latex;make clean;

theory:
	cd HOL;make;
	cd Latex;make;

update:
	make clean;make;
